#### Autori: Domenico Lembo, Antonella Poggi, Giuseppe Santucci and Marco Schaerf

[Dipartimento di Ingegneria informatica, automatica e gestionale](https://www.diag.uniroma1.it)

<img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.eu.png"
     alt="License"
     style="float: left;"
     height="40" width="100" />
This notebook is distributed with license Creative Commons *CC BY-NC-SA*

# La libreria NumPy
1. NumPy
2. Il tipo array di NumPy
3. Creazione di un array in NumPy
4. Rappresentazione interna degli array ed i metodi `reshape()` e `flatten()`
5. Attributi, operatori e funzioni della classe `ndarray` (array)
6. Indicizzazione, slicing e iterazione
7. Lettura di un array da file
8. Esercizi su matrici come NumPy array

## Numpy
Questa lezione è basata sul tutorial [Quickstart](https://numpy.org/devdocs/user/quickstart.html) del sito ufficiale di [NumPy](https://numpy.org/) (in inglese).
Per eseguire questo notebook dovete installare sul vostro computer il modulo numpy, istruzioni dettagliate sono disponibili [qui](https://scipy.org/install.html), comunque per la maggior parte delle installazioni dovete solo aprire una shell di comandi e dare il comando: `pip3 install numpy`; per installarlo nell'ambiente  notebook dovete dare il comando  `%pip3 install numpy`.

Perchè? Ottimizzazione!

NumPy fa parte di un pacchetto di moduli Python per il calcolo scientifico, noi vedremo, brevemente, anche [Matplotlib](https://matplotlib.org/).

In [2]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/ad/11/52fbe97fd84c91105b651d25a122f8deed6d3519afb14f9771fac1c9b7de/numpy-1.26.3-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 320.0 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 542.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 4.3 MB/s eta 0:00:04
   - -------------------------------------- 0.5/15.5 MB 6.8 MB/s eta 0:00:03
   -- ------------------------------------- 1.0/15.5 MB 7.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/15.5 MB 8.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 8.4 MB/s eta 0:00:02
   ----- ---------------------------------- 2.3/15.5 MB 8.6 MB/s eta 0:00:02
   ------- --------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## Il tipo array di NumPy 
L'oggetto principale di NumPy è l'array multidimensionale **omogeneo**. È una tabella di elementi (solitamente numeri), tutti dello stesso tipo, indicizzati da una tupla di numeri interi non negativi. In NumPy le dimensioni sono chiamate assi.

Ad esempio, le coordinate di un punto nello spazio \[1, 2, 1\] sono rappresentate su un asse. L'asse contiene 3 elementi, quindi diciamo che ha una lunghezza di 3. 

Nell'esempio mostrato di seguito, l'array ha 2 assi. Il primo asse ha una lunghezza di 2, il secondo asse ha una lunghezza di 3.

\[\[1., 0., 0.\],
 \[0., 1., 2.\]\]
 
N.B. per evitare qualunque confusione useremo i due termini:

- asse/i: coordinata/e dell'array
- lunghezza asse (o dimensione asse): numero di elementi presenti in un asse

Un array 3D (tridimensionale) ha tre assi :-).  La dimensione degli assi ha una lunghezza che dipende dal numero di elementi inseriti.
 
La classe di array di NumPy si chiama *ndarray*. È anche conosciuto con l'alias *array*. Notate che numpy.array non è uguale alla classe Standard Python Library array.array, che gestisce solo array 1D e offre molte meno funzionalità.

- *ndarray.ndim*: numero degli assi

- *ndarray.shape*: è una tupla di ndim interi che contiene la lunghezza di ogni asse

- *ndarray.size*: numero complessivo di elementi dell'array

Un esempio:
 

In [6]:
import numpy as np

#Creiamo, ad esempio, un array a due assi 2x3 (cioè con 2 righe e 3 colonne)
a = np.array([[1., 0., 0.],[0., 1., 2.]])

print(a)

print('numero assi=',a.ndim)
print('shape=',a.shape)
print('numero elementi=',a.size)


[[1. 0. 0.]
 [0. 1. 2.]]
numero assi= 2
shape= (2, 3)
numero elementi= 6


Per accedere a un elemento di indici `i` e `j` di un array bidimensionale `m` si può usare la notazione delle liste di liste (cioé `m[i][j]`) oppure la notazione semplificata `m[i,j]`. Ovviamente, questo è valido anche per array di dimensione superiore a 2.

Un esempio:

In [12]:
import numpy as np

#Creiamo, ad esempio, un array 2x3 (cioè con 2 righe e 3 colonne)
a = np.array([[1., 0., 0.],[0., 1., 2.]])
print(type(a))
print('a=',a)
print()
#Stampiamo uno specifico elemento, ad esempio,
#quello sulla riga 0 colonna 1
print('elemento riga 0 colonna 1',a[0][1]) #notazione standard per liste di liste
print('elemento riga 0 colonna 1',a[0,1]) #notazione semplificata di NumPy
# stampa tramite doppio ciclo 

print()
for i in range(a.shape[0]):       # righe
    for j in range(a.shape[1]):   # colonne
        print(a[i,j],end='\t')
    print()

<class 'numpy.ndarray'>
a= [[1. 0. 0.]
 [0. 1. 2.]]

elemento riga 0 colonna 1 0.0
elemento riga 0 colonna 1 0.0

1.0	0.0	0.0	
0.0	1.0	2.0	


## Creazione di un array in NumPy
Ci sono molti modi per creare un array in NumPy, si può direttamente creare un array fornendo tutti i dati, come visto sopra, si può trasformare una lista in array oppure si possono usare le numerose funzioni di inizializzazione presenti in NumPy. **Notate che le dimensioni degli assi dell'array vanno fornite come tuple**, cioè scritte tra parentesi. 

La funzione *print()* applicata ad un oggetto di tipo array lo stampa automaticamente per righe, se è tridimensionale stampa un piano 2D per volta. Vediamo degli esempi:

In [14]:
# Crea un array 2D di uno con 3 righe e 4 colonne
print(np.ones((3,4))) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Si noti che nell'esempio sopra, la tupla (3,4) è la shape dell'array e denota contemporaneamente:
- il numero degli assi (lunghezza della tupla)
- la lunghezza di ciascun asse (valori della tupla)

La stampa di un array con 3 o più assi richiede stampe ripetute:

In [15]:
# Crea un array 3D di zeri con shape 2x3x4 ed ogni elemento di tipo intero (con segno) a 16 bit
print(np.zeros((2,3,4),dtype=np.int16)) #notate la stampa fatta di 2 matrici 3x4

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [18]:
# Crea un array 2D di valori casuali (random)
print(np.random.random((2,2)))

[[0.57798644 0.96217855]
 [0.29942085 0.86041023]]


In [19]:
# Crea un array 2D vuoto 
print(np.empty((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [20]:
# Crea un array 2D pieno con il valore 7 (tutti gli elementi valgono 7)
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [21]:
# Crea un array 1D con i valori da 10 a 50 (escluso) con passo 5
print(np.arange(10,50,5))

[10 15 20 25 30 35 40 45]


In [34]:
# Crea un array 1D con 9 valori uniformemente spaziati tra 0 e 2 (inclusi)
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## Rappresentazione interna degli array ed i metodi `reshape()` e `flatten()`
NumPy rappresenta in memoria gli array usando zone contigue di memoria. Di fatto, l'array viene rappresentato sempre **come un array monodimensionale**, dove le righe vengono scritte una dopo l'altra. Un array di dimensioni (3,4) e un array di dimensioni (2,3,2) sono rappresentati in memoria nella stessa maniera: un array monodimensionale di 12 elementi (12). Per questo motivo, è possibile cambiare facilmente **la shape**  lasciando invariato il numero degli elementi, ovvero la **size**, usando il metodo `reshape()`. Se vogliamo trasformare un array nella sua versione monodimensionale possiamo usare il metodo `flatten()`. Vediamo degli esempi:

In [39]:
a = np.random.random((3,4)) #12 elementi, shape (3,4)
print(a)

[[0.19608785 0.57427444 0.22051577 0.8164005 ]
 [0.87629121 0.4274371  0.60690242 0.94974681]
 [0.05957049 0.67226671 0.11852439 0.5752485 ]]


In [40]:
b = a.reshape((2,3,2)) #12 elementi, shape (2,3,2)
print(b)
d = a.reshape((2,5))
print(d)

[[[0.19608785 0.57427444]
  [0.22051577 0.8164005 ]
  [0.87629121 0.4274371 ]]

 [[0.60690242 0.94974681]
  [0.05957049 0.67226671]
  [0.11852439 0.5752485 ]]]


ValueError: cannot reshape array of size 12 into shape (2,5)

In [41]:
c = a.flatten() #oppure c = a.reshape((12))
print(c)

[0.19608785 0.57427444 0.22051577 0.8164005  0.87629121 0.4274371
 0.60690242 0.94974681 0.05957049 0.67226671 0.11852439 0.5752485 ]


## Attributi, operatori e funzioni della classe ndarray (array)
Oltre agli attributi **ndim**, **shape**, e **size**, già introdotti in precedenza, la classe ndarray offre:

- **dtype**: il tipo di elementi nella matrice. Si può creare o specificare i tipi usando i tipi standard di Python. Inoltre NumPy fornisce tipi propri: numpy.int32, numpy.int16 e numpy.float64 sono alcuni esempi.
- **itemsize**: la dimensione in byte di ciascun elemento dell'array. Ad esempio, un array di elementi di tipo float64 ha itemsize 8 (= 64/8), mentre uno di tipo complex32 ha itemsize 4 (= 32/8). È equivalente a ndarray.dtype.itemsize.

- +, \-, \*, \*\*, \\, <, =, > :  operatori che operano su **tutta** la matrice 


In [45]:
a = np.array ([2,3,4])
print('dtype=',a.dtype)
b = np.array ([1.2, 3.5, 5.1])
print('dtype=',b.dtype)
c = np.array([[1,2], [3,4]], dtype = complex)
print(c)
print('dtype=',c.dtype)

dtype= int32
dtype= float64
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
dtype= complex128


### Operazioni di base
Gli operatori aritmetici sugli array si applicano a tutti gli elementi. Di regola, un nuovo array viene creato e riempito con il risultato.

In [46]:
a = np.array ([20,30,40,50])
b = np.array ([4,4,4,4])
c = a-b
print(c)
print()
print('a*7=',a*7)
print('a*b=',a*b)

[16 26 36 46]

a*7= [140 210 280 350]
a*b= [ 80 120 160 200]


In [47]:
print(b**2)
print(np.sin(a))

[16 16 16 16]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]


In [48]:
print(a)
print(a < 35)

[20 30 40 50]
[ True  True False False]


N.B. A differenza di molti linguaggi a matrice, l'operatore del prodotto * opera elemento per elemento negli array NumPy, cioè moltiplica gli elementi nella stessa posizione dei 2 arrays, che devono avere le stesse dimensioni. Il prodotto tra matrici può essere eseguito utilizzando l'operatore @ (in python> = 3.5) o il metodo dot()

In [49]:
A = np.array([[1,1],
              [0,1]]) 
B = np.array ([[2,0],
               [3,4]])
print(A * B) # è il prodotto elemento per elemento
print(A @ B) # è il prodotto tra matrici
print(A.dot(B)) # un altro prodotto tra matrici
  
# A @ B =     [1,1]   [2,0]      [1*2+1*3, 1*0+1*4]     [5,4]
#             [0,1]   [3,4]      [0*2+1*3, 0*0+1*4]     [3,4]

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Alcune operazioni, come += e \*=, agiscono per modificare un array esistente anziché crearne uno nuovo.

In [50]:
a = np.ones((2,3), dtype = int)
print(a)

a *= 3
print(a)

[[1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]]


Molte operazioni unarie, come calcolare la somma di tutti gli elementi dell'array, sono implementate come metodi della classe ndarray.

In [54]:
a = np.random.random((2,3))
print(a)
print('sum=',a.sum())
print('a+a=',a+a)
print('min=',a.min())
print('max=',a.max())

[[0.92966586 0.65325584 0.66648273]
 [0.87965018 0.72267336 0.01079827]]
sum= 3.862526240489123
a+a= [[1.85933172 1.30651168 1.33296547]
 [1.75930035 1.44534672 0.02159655]]
min= 0.010798274028666732
max= 0.9296658594162184


In [57]:
a = np.random.random((2,3))
print('a=',a)
b = np.random.random(10)
print('b=',b)

# per trovare l'indice in cui si trova il massimo (od il minimo) si può usare
# la funzione (NON METODO) argmax (argmin). Se l'array è monodimensionale restituisce
# l'indice, altrimenti restituisce l'indice dell'array flat (appiattito) in cui tutte
# le righe sono messe di seguito. In caso di più elementi pari al massimo (o minimo) 
# argmax restituisce l'indice più piccolo fra tutti quelli 

print('argmax_b',np.argmax(b))
print('argmin_b',np.argmin(b))

print('argmax_a',np.argmax(a)) #di [0.96961376 0.9839157  0.36553127 0.2911096  0.92764884 0.62635703]
print('argmin_a',np.argmin(a)) #di [0.96961376 0.9839157  0.36553127 0.2911096  0.92764884 0.62635703]

a= [[0.41674604 0.80452116 0.42675276]
 [0.48897789 0.00931901 0.6015321 ]]
b= [0.46503017 0.68363798 0.9998155  0.65427169 0.5920402  0.90380766
 0.92539217 0.86991664 0.37889761 0.84823625]
argmax_b 2
argmin_b 8
argmax_a 1
argmin_a 4


Per impostazione predefinita, queste operazioni si applicano all'array come se fosse un elenco di numeri, indipendentemente dalla sua forma. Tuttavia, specificando il parametro axis è possibile applicare un'operazione lungo l'asse specificato di un array:

In [60]:
a = np.random.random((2,3))
print('a=',a)
print()
# somma di ogni colonna, restituisce un array con una dimensione in meno
print('somma delle colonne=', a.sum(axis = 0))
print()
print('somma delle righe=', a.sum(axis = 1))

a= [[0.72118327 0.34176791 0.36502927]
 [0.89727663 0.70382622 0.68914432]]

somma delle colonne= [1.6184599  1.04559412 1.05417359]

somma delle righe= [1.42798045 2.29024717]


In [61]:
# min di ogni riga, restituisce un array con una dimensione in meno
b = np.random.random((3,2))
print(b)
print()
print('Minimo lungo l\'asse 0:',b.min(axis = 0))    #colonne
print('Minimo lungo l\'asse 1:',b.min(axis = 1))    #righe

[[0.37458253 0.16183428]
 [0.90171862 0.99709906]
 [0.36436481 0.3275578 ]]

Minimo lungo l'asse 0: [0.36436481 0.16183428]
Minimo lungo l'asse 1: [0.16183428 0.90171862 0.3275578 ]


In [64]:
# somma cumulativa lungo ogni asse
print(b)
print()
print('Somma cumulativa lungo l\'asse 0:\n',b.cumsum(axis = 0))
print()
print('Minimo lungo l\'asse 1:\n',b.cumsum(axis = 1))

[[0.37458253 0.16183428]
 [0.90171862 0.99709906]
 [0.36436481 0.3275578 ]]

Somma cumulativa lungo l'asse 0:
 [[0.37458253 0.16183428]
 [1.27630115 1.15893335]
 [1.64066596 1.48649115]]

Minimo lungo l'asse 1:
 [[0.37458253 0.53641681]
 [0.90171862 1.89881769]
 [0.36436481 0.69192261]]


## Indicizzazione, slicing e iterazione
Le matrici multidimensionali possono essere indicizzate, suddivise e ripetute, in modo simile alle liste e ad altre sequenze di Python, ma anche **contemporaneamente** su più assi usando la notazione semplificata. Attraverso lo slicing si può, ad esempio, estrarre una colonna della matrice od anche le colonne dispari. Vediamo alcuni esempi.

In [65]:
b = np.arange(9) #crea array 1D di 9 elementi da (ovvero con tutti gli interi da 0 a 9, con passo 1)
print(b)

[0 1 2 3 4 5 6 7 8]


In [66]:
print(b[2])      # stampa l'elemento di indice 2
print(b[1:8:2])  # da indice 1 a indice 8 (escluso) passo 2 

2
[1 3 5 7]


In [70]:
b = np.arange(12) #crea array 1D di 12 elementi
print(b)
d=b[::-1] #restituisce un array 1D invertendo il contenuto di b

print(d.shape)  #indica quanti elementi ha l'array
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[11 10  9  8  7  6  5  4  3  2  1  0]


In [71]:
# Consideriamo ora un caso a 2D 

c = np.arange(20).reshape(4,5) #crea array 4x5 da un array 1D di 20 elementi
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [79]:
print('l\'elemento in posizione 2,3 è',c[2,3]) # stampa l'elemento di indice 2, 3
print(c[1:4:2,:]) # stampa per le righe 1 e 3, tutte le colonne (la virgola separa la parte delle righe da quello delle colonne)
                  # righe=(1:4:2) 2 indica il passo
                  # colonne=(:)

l'elemento in posizione 2,3 è 13
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [80]:
print(c)
print()
print(c[0:2,0:3]) # seleziona e stampa le righe 0 e 1 e le colonne 0, 1, e 2

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[0 1 2]
 [5 6 7]]


In [81]:
print(c)
print()
print(c[1:3,1:4]) # seleziona e stampa le righe 1 e 2 e le colonne 1, 2 e 3

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 6  7  8]
 [11 12 13]]


In [82]:
print(c)
print()
print(c[:,::2]) # seleziona e stampa le colonne pari

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]]


In [87]:
print(c)
print()
d=c[:,2:3] #seleziona la colonna 2
print('la dimensione dell\'array c[:,2:3] è', d.shape)
print('il suo tipo è',d.dtype)
print(d)
e=c[:,2]
print('la dimensione dell\'array c[:,2] è', e.shape)
print('il suo tipo è',e.dtype)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

la dimensione dell'array c[:,2:3] è (4, 1)
il suo tipo è int32
[[ 2]
 [ 7]
 [12]
 [17]]
la dimensione dell'array c[:,2] è (4,)
il suo tipo è int32
[ 2  7 12 17]


In [88]:
# Vediamo ora degli esempi di iterazioni  con la print()
b = np.arange(4) #crea array 1D di 4 elementi
print('b=',b)
print()
for elem in b:
    print(elem ** 2) # calcola il quadrato degli elementi di b e stampa ciascun valore su una riga diversa

b= [0 1 2 3]

0
1
4
9


In [93]:
c = np.arange(6).reshape(2,3) #crea array 2x3 da un array 1D di 6 elementi
print(c)
print()
print('c[0]=',c[0])
print()
for riga in c:
    print(riga ** 2) # calcola, riga per riga, il quadrato degli elementi

[[0 1 2]
 [3 4 5]]

c[0]= [0 1 2]

[0 1 4]
[ 9 16 25]


In [94]:
for i in range(c.shape[0]):    # stampa ciascun valore di c su una riga diversa
    for j in range(c.shape[1]):
        print(c[i,j]) 

0
1
2
3
4
5


In [95]:
for riga in c:    # versione alternativa che itera sugli elementi e non sugli indici
    for elem in riga:
        print(elem)

0
1
2
3
4
5


## Lettura di un array da file
NumPy offre il metodo loadtxt() per leggere un file nel seguente formato:

`numero`<sub>1,1</sub> `numero`<sub>1,2</sub> `numero`<sub>1,3</sub> .... `numero`<sub>1,n</sub>

`numero`<sub>2,1</sub> `numero`<sub>2,2</sub> `numero`<sub>2,3</sub> .... `numero`<sub>2,n</sub>
........

`numero`<sub>m,1</sub> `numero`<sub>m,2</sub> `numero`<sub>m,3</sub> .... `numero`<sub>m,n</sub>

e restituisce un `nd.array` 2D con tutti i valori contenuti nel file.

In [96]:
print(np.loadtxt("array1.txt"))

[[ 0.5  10.2   3.5   2.3   3.1  -1.33]
 [ 0.5  11.2  -3.5   1.3   3.1  -2.33]
 [ 1.5   1.2   3.75 -2.3   3.1  -1.33]]


Se il file contiene una sola riga, viene restituito un array 1D

In [97]:
print(np.loadtxt("array2.txt"))

[ 0.5  10.2   3.4   2.3   3.1  -1.33]


Se il file non contiene lo stesso numero di colonne in ogni riga, la lettura va in errore:

In [98]:
print(np.loadtxt("array3.txt"))

ValueError: the number of columns changed from 6 to 5 at row 3; use `usecols` to select a subset and avoid this error

### lettura da file csv
Se il file invece di avere lo spazio come separatore ha la ',' (o un altro separatore), basta specificare quale è il delimitatore (delimiter)

In [99]:
print(np.loadtxt("array1.csv", delimiter = ','))

[[ 0.5  10.2   3.5   2.3   3.1  -1.33]
 [ 0.5  10.2   3.5   2.3   3.1  -1.33]
 [ 0.5  10.2   3.5   2.3   3.1  -1.33]]


## Esercizi su matrici come NumPy array

1. Esercizio: Ricerca dell'elemento massimo: Funzione che prende in input una matrice e restituisce il valore massimo presente; assume che la matrice non sia vuota. 
2. Esercizio: Ricerca della riga a somma massima: Funzione che prende in input una matrice e restituisce l'indice della riga di somma massima presente; assume che la matrice non sia vuota e che nel caso ci siano più righe di somma massima la funzione restituisca la riga con indice minore.
3. Esercizio: Somma di matrici (stessa dimensione).
4. Esercizio: Prodotto di matrici (dimensioni compatibili).

In [100]:
# Creiamo 2 matrici 4x3 a e b ed una matrice c 3x4, tutte con numeri random
a = np.random.random((4,3))
b = np.random.random((4,3))
c = np.random.random((3,4))
print(a)
print()
print(b)
print()
print(c)
print()

[[0.56651958 0.24470832 0.50843894]
 [0.46746988 0.56398491 0.84503163]
 [0.99059681 0.17600973 0.91187859]
 [0.40811876 0.56645412 0.83765312]]

[[0.12157779 0.34970613 0.1328542 ]
 [0.95273868 0.68509803 0.75339369]
 [0.81062855 0.48528743 0.34872088]
 [0.8499591  0.5197259  0.02645752]]

[[0.42752976 0.96345793 0.05100826 0.80541655]
 [0.66478268 0.86215975 0.97893286 0.69183664]
 [0.74167964 0.01415158 0.34691716 0.44433635]]



In [101]:
# Esercizio 1: basta usare la funzione np.max()
print(a)
print(np.max(a))

[[0.56651958 0.24470832 0.50843894]
 [0.46746988 0.56398491 0.84503163]
 [0.99059681 0.17600973 0.91187859]
 [0.40811876 0.56645412 0.83765312]]
0.9905968147118269


In [102]:
# Esercizio 2: Scansiona le righe e trova il massimo
print(a)
sommarighe = np.sum(a,axis=1) #calcolo il vettore somma delle righe
print(sommarighe)

print(np.argmax(sommarighe)) #restituisco l'indice dell'elemento massimo

[[0.56651958 0.24470832 0.50843894]
 [0.46746988 0.56398491 0.84503163]
 [0.99059681 0.17600973 0.91187859]
 [0.40811876 0.56645412 0.83765312]]
[1.31966684 1.87648641 2.07848513 1.81222601]
2


In [103]:
# Esercizio 3: basta usare l'operatore +
print(a+b) # Il risultato ha le stesse dimensioni di a e b

[[0.68809737 0.59441445 0.64129314]
 [1.42020856 1.24908293 1.59842532]
 [1.80122537 0.66129716 1.26059947]
 [1.25807786 1.08618002 0.86411064]]


In [104]:
# Esercizio 4: basta usare l'operatore @
print(a@c) # Poiché a è 4x3 e c 3x4 il risultato è un array 4x4

[[0.78198064 0.76399066 0.44483638 0.85150033]
 [1.20152744 0.94859118 0.86910416 1.14217167]
 [1.21683962 1.11905139 0.53917666 1.32479385]
 [1.17232207 0.89343332 0.86593423 1.09279906]]


#### Esercizio: calcolo del più grande punto di sella
Scrivere una funzione che prende in input un array bidimensionale **a** e restituisce (se esiste) la tupla (i,j) della posizione del più grande punto di sella presente nell'array. Se non esiste deve restituire la tupla (-1,-1). Si definisce *punto di sella (i,j)* una posizione tale che a\[i,j\] è il **minimo valore della riga i** e il **massimo valore della colonna j** o viceversa. Assumete, per semplicità, che ogni riga e ogni colonna abbia uno e un solo massimo e minimo.

In [105]:
import numpy as np

def maxPuntoSella(a):
    ris = (-1,-1) # per ora non ho trovato punti di sella
    minrighe = np.argmin(a,axis=1) # Trova gli indici dei minimi per riga e.g. [4, 1, 1, 4, 4])
    maxrighe = np.argmax(a,axis=1) # Trova gli indici dei massimi per riga
    mincol = np.argmin(a,axis=0) # Trova gli indici dei minimi per colonna
    maxcol = np.argmax(a,axis=0) # Trova gli indici dei massimi per colonna
    # un punto di sella (i,j) minimo sulle righe e massimo sulle colonne ha la proprietà che
    # j = minrighe[i] e i = maxcol[j], la colonna j è la minima sulla riga i e la riga i
    # è la massima nella colonna j. per l'altro tipo di punto di sella vale il simmetrico
    for i in range(a.shape[0]):
        j = minrighe[i] # cerco punti di sella minriga-maxcol
        if i == maxcol[j]: # Trovato un punto di sella minriga-maxcol
            if ris == (-1,-1): # primo punto di sella trovato
                ris = (i,j)
            elif a[i,j] > a[ris]: # Trovato un nuovo punto di sella, più grande del massimo precedente
                ris = (i,j)
        j = maxrighe[i] # cerco punti di sella maxriga-mincol
        if i == mincol[j]: # Trovato un punto di sella maxriga-mincol 
            if ris == (-1,-1): # primo punto di sella trovato
                ris = (i,j)
            elif a[i,j] > a[ris]: # Trovato un nuovo punto di sella, più grande del massimo precedente
                ris = (i,j)
    return ris

In [106]:
ps=(-1,-1)
while ps==(-1,-1):
    a=np.random.random((5,5))
    ps=maxPuntoSella(a)
print(a,maxPuntoSella(a))

[[0.87042376 0.52699357 0.46370222 0.7646989  0.23714434]
 [0.59917603 0.77851099 0.33160482 0.26235236 0.35474939]
 [0.82769057 0.39684053 0.12543879 0.56734361 0.53954194]
 [0.42889899 0.22643297 0.09552203 0.27170772 0.05268543]
 [0.66150139 0.76233083 0.68033128 0.58532054 0.8313214 ]] (3, 0)


### Altre funzioni e librerie
Python ha un numero molto elevato di altri moduli e librerie predefinite che sono a disposizione dei programmatori, quali ad esempio [SciPy](https://www.scipy.org/) per il calcolo scientifico, [Pandas](https://pandas.pydata.org/) per l'analisi dei dati, [Keras](https://keras.io/), [TensorFlow](https://www.tensorflow.org/) e [PyTorch](https://pytorch.org/) per il cosiddetto *deep learning* e molte altre. Qui ora mostriamo solo alcune funzionalità della libreria *IPython.display* per la gestione delle immagini.

#### Caricare, visualizzare e cancellare immagini
La libreria IPython.display ci mette a disposizione 3 funzioni per le immagini, cioè le funzioni *Image*, *display* e *clear_output*. Il loro comportamento è il seguente:
- La funzione `Image(url)` carica un immagine da un indirizzo web (url) o e restituisce un oggetto di tipo image
- La funzione `display(image)` visualizza sullo schermo un oggetto di tipo image
- la funzione `clear_output()` cancella quanto visualizzato dalla cella.

Vediamo un semplice esempio:

In [107]:
from IPython.display import display, Image, clear_output

url1 = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Interno_del_Colosseo.jpg/281px-Interno_del_Colosseo.jpg"
url2 = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Colosseum_in_Rome-April_2007-1-_copie_2B.jpg/390px-Colosseum_in_Rome-April_2007-1-_copie_2B.jpg"

image1 = Image(url1) # carica l'immagine alla url1 nell'oggetto image1
image2 = Image(url2) # carica l'immagine alla url2 nell'oggetto image2
image3=Image(open('Eiffel.png',"rb").read())
display(image1) # visualizza image1
input() # il programma aspetta un invio ('enter') prima di andare avanti
clear_output() # cancella output
display(image2) # visualizza image1
input() # il programma aspetta un invio ('enter') prima di andare avanti
clear_output() # cancella output
display(image3) # visualizza image2
input() # il programma aspetta un invio ('enter') prima di andare avanti
clear_output() # cancella output e termina


## Esercizi
Completate questi esercizi prima di cominciare il prossimo argomento

### Esercizio 1:
Scrivere una funzione che riceve in input il nome di un file contenente un array 2D e restituisce la lista degli indici delle righe che contengono il massimo numero di valori strettamente positivi. Assumere che il file sia ben formato, cioè tutte le righe contengono lo stesso numero di elementi.

In [111]:
import numpy as np
fin=open('array1.txt','r',encoding='UTF-8')
testo=fin.read()
maxri=np.argmax(testo)

0
.
5
 
1
0
.
2
 
3
.
5
 
2
.
3
 
3
.
1
 
-
1
.
3
3


0
.
5
 
1
1
.
2
 
-
3
.
5
 
1
.
3
 
3
.
1
 
-
2
.
3
3


1
.
5
 
1
.
2
 
3
.
7
5
 
-
2
.
3
 
3
.
1
 
-
1
.
3
3


### Esercizio 2:
Scrivere una funzione che riceve in input il nome di un file contenente un array 2D e restituisce la colonna il cui valore medio sia, in valore assoluto, più piccolo. Assumere che il file sia ben formato, cioè tutte le righe contengono lo stesso numero di elementi.

In [ ]:
import numpy as np

